# Source: jenkins-x-crds/templates/sourcerepositories-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sourcerepositories.jenkins.io
spec:
  conversion:
    strategy: None
  group: jenkins.io
  names:
    categories:
    - all
    kind: SourceRepository
    listKind: SourceRepositoryList
    plural: sourcerepositories
    shortNames:
    - sourcerepo
    - srcrepo
    - sr
    singular: sourcerepository
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
    - jsonPath: .spec.url
      description: The URL of the git repository
      name: URL
      type: string
    - jsonPath: .spec.description
      description: A description of the source code repository - non-functional user-data
      name: Description
      type: string
    schema:
      openAPIV3Schema:
        description: SourceRepository is the metadata for an Application/Project/SourceRepository
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          spec:
            description: SourceRepositorySpec provides details of the metadata for an
              App
            properties:
              description:
                type: string
              httpCloneURL:
                description: HTTPCloneURL is the git URL to clone this repository using
                  HTTP/HTTPS
                type: string
              org:
                type: string
              provider:
                description: Provider stores the URL of the git provider such as https://github.com
                type: string
              providerKind:
                description: ProviderKind is the kind of provider (github / bitbucketcloud
                  / bitbucketserver etc)
                type: string
              providerName:
                description: ProviderName is a logical name for the provider without
                  any URL scheme which can be used in a label selector
                type: string
              repo:
                type: string
              scheduler:
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                    type: string
                  uid:
                    description: 'UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids'
                    type: string
                required:
                - kind
                - name
                type: object
              sshCloneURL:
                description: SSHCloneURL is the git URL to clone this repository using
                  SSH
                type: string
              url:
                description: URL is the web URL of the project page
                type: string
            type: object
        type: object
status:
  acceptedNames:
    categories:
    - all
    kind: SourceRepository
    listKind: SourceRepositoryList
    plural: sourcerepositories
    shortNames:
    - sourcerepo
    - srcrepo
    - sr
    singular: sourcerepository
  conditions:
  - lastTransitionTime: "2020-03-30T19:10:45Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
