# Source: kuberhealthy/crds/khstate.yaml---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khstates.comcast.github.io
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'customresourcedefinitions'
spec:
  group: comcast.github.io
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - description: OK status
          jsonPath: .spec.OK
          name: OK
          type: string
        - description: Last Run
          jsonPath: .spec.LastRun
          name: Age LastRun
          type: date
        - description: Age
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          description: description
          type: object
  scope: Namespaced
  names:
    plural: khstates
    singular: khstate
    kind: KuberhealthyState
    shortNames:
      - khs