# Source: kuberhealthy/crds/khjob.yaml---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khjobs.comcast.github.io
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'customresourcedefinitions'
spec:
  group: comcast.github.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: description
          type: object
  scope: Namespaced
  names:
    plural: khjobs
    singular: khjob
    kind: KuberhealthyJob
    shortNames:
      - khj